version: '3.0'

services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - flask-app